package com.example.recipe_book.data.model

import kotlinx.serialization.Serializable

// Serialization is the process of converting data used by an application to a format that can be
// transferred over a network, or stored in a database or a file.
// Here the code is automatically generated by the Kotlin Serialization plugin.
@Serializable
data class ProductResponse(
    val data: List<Recipe>
)

@Serializable
data class Recipe(
    val name: String,
    val ingredients: Map<String, String>,
    val steps: List<String>,
    val notes: String,
    val picture: String = "" //Platzhalter
)